version: '3.8'

# fuente: https://zgadzaj.com/development/docker/docker-compose/containers/rabbitmq

services:
    rabbit.service:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        volumes:
            - ./etc/:/etc/rabbitmq/
            - ./data/:/var/lib/rabbitmq/
            - ./logs/:/var/log/rabbitmq/
        ports:
            - 5672:5672
            - 15672:15672